Const std::string & support
PicsArt/luabind pull request #2
Opened 2023-01-12 11:29 UTC by liana-mazayan

Add const std::string& support. 
Add compile-time error for std::string* 
Modify valid_lua_arg to accept * types as it is supported for everything other than std::string
Move lua_test to lua_test.hpp in order to use from tests.
Add test for const std::string& binding.

2023-01-12 11:44 UTC, davits requested changes
Thanks!

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/PicsArt/luabind/2#-:-NL_mw3y8v0Z0-u5MbRy:b-ucfknh)* status: all files reviewed, 1 unresolved discussion (waiting on @liana-mazayan and @tigrangs)

___
*[`include/luabind/traits.hpp` line 69 at r1](https://reviewable.io/reviews/PicsArt/luabind/2#-NL_mMjy-qgrKTxfTImf:-NL_mMjy-qgrKTxfTImg:b-sgh4qb) ([raw file](https://github.com/PicsArt/luabind/blob/edb028940fade1c2f9b2bb7bdc2a079c47038031/include/luabind/traits.hpp#L69)):*
> ```cpp
>     : std::bool_constant<!is_pointer_ref_v<T> &&
>                          ((std::is_fundamental_v<T> && !std::is_pointer_v<T> && !std::is_reference_v<T>) ||
>                           std::is_class_v<T> || std::is_class_v<std::remove_cvref_t<T>> || std::is_class_v<std::remove_pointer<T>>)> {};
> ```

`std::is_class_v<T> || std::is_class_v<std::remove_cvref_t<T>>` <=> `std::is_class_v<std::remove_cvref_t<T>`


<!-- Sent from Reviewable.io -->

2023-01-12 13:43 UTC, tigrangs approved these changes
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/PicsArt/luabind/2)* status: all files reviewed, 1 unresolved discussion (waiting on @liana-mazayan)



<!-- Sent from Reviewable.io -->

2023-01-13 11:32 UTC, liana-mazayan reviewed
> *[Reviewable](https://reviewable.io/reviews/PicsArt/luabind/2)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @davits and @tigrangs)

___
*[`include/luabind/traits.hpp` line 69 at r1](https://reviewable.io/reviews/PicsArt/luabind/2#-NL_mMjy-qgrKTxfTImf:-NLethpTApz_GND-6XJQ:b-896fix) ([raw file](https://github.com/PicsArt/luabind/blob/edb028940fade1c2f9b2bb7bdc2a079c47038031/include/luabind/traits.hpp#L69)):*
<details><summary><i>Previously, davits (Davit Samvelyan) wrote…</i></summary><blockquote>

`std::is_class_v<T> || std::is_class_v<std::remove_cvref_t<T>>` <=> `std::is_class_v<std::remove_cvref_t<T>`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-13 12:51 UTC, tigrangs approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/PicsArt/luabind/2#-:-NLfAjNlEBqWBcoE3hUo:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @davits)



<!-- Sent from Reviewable.io -->

2023-01-17 08:24 UTC, davits commented
Welcome to the open source world.





<!-- Sent from Reviewable.io -->

2023-01-17 08:24 UTC, davits approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/PicsArt/luabind/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @liana-mazayan)



<!-- Sent from Reviewable.io -->

2023-01-17 08:27 UTC, merged